### ISSUE TITLE
Need basic mockup of UI Screens

### ISSUE THREAD

**Issue by scottleyg** [KyleWheeler19/Senior-Project#2]
If there is nothing else that we talked about last week to do, go to https://draw.io or similar and make some quick mockups for each screen (or even just one summary screen).

You can use draw.io also for architectural diagrams, too.

**Comment by KyleWheeler19** [comment]
I think I did this properly:

![initialhomescreendesign](https://cloud.githubusercontent.com/assets/22205375/19421996/057575ea-93c2-11e6-9315-63de097773f2.png)

![initialnewtaskdesign](https://cloud.githubusercontent.com/assets/22205375/19422041/d9368496-93c2-11e6-9421-3b93ad073b4a.png)

![initialinfodesign](https://cloud.githubusercontent.com/assets/22205375/19422046/0d476e94-93c3-11e6-9458-6c32034f2ec8.png)

**Comment by scottleyg** [comment]
Looks great! Closing this issue.
