### ISSUE TITLE
Create Application "Stub" with layouts

### ISSUE THREAD

**Issue by scottleyg** [KyleWheeler19/Senior-Project#5]
Based on the mockups you defined.  Create a new Android Studio Project with the task list as the main activity.

You will need the following UI elements:
1) a text view element for the title
2) List View element for the list of tasks
3) a plus button to add new tasks.  

from there we can build the actions and the rest of the "activities"

when you are done, commit the code to the github repository and we can walk through the actions.

**Comment by scottleyg** [comment]
I have gotten a quick stub project up and running, so I can help deal with language/SDK/IDE issues you have.  use your understanding of the features to create the UI layouts and then we will create issues for each of the buttons, actions, etc.

**Comment by KyleWheeler19** [comment]
![image](https://cloud.githubusercontent.com/assets/22205375/19629797/58610ab6-9931-11e6-8e22-56b090767537.png)

**Comment by KyleWheeler19** [comment]
![image](https://cloud.githubusercontent.com/assets/22205375/19753359/d50fb6dc-9bb8-11e6-95e8-c78c8b469cc5.png)
